from pathlib import Path

from playwright.sync_api import Page, expect

from tests.e2e.conftest import WORKSPACE
from tests.e2e.helpers import open_readme, wait_for_preview


def test_loads_markdown_sidebar_and_diagrams(page: Page) -> None:
    open_readme(page)
    expect(page.locator("#nav a.nav-link.active").filter(has_text="README.md")).to_be_visible()
    page.locator("#nav summary").filter(has_text="docs").click()
    expect(page.locator("#nav a.nav-link", has_text="install.md")).to_be_visible()
    expect(page.locator("#content .diagram-mermaid svg")).to_be_visible()
    expect(page.locator("#toc a", has_text="Diagrams")).to_be_visible()


def test_theme_toggle_switches_data_theme(page: Page) -> None:
    open_readme(page)
    html = page.locator("html")
    expect(html).to_have_attribute("data-theme", "light")
    page.locator("#theme-toggle").click()
    expect(html).to_have_attribute("data-theme", "dark")
    wait_for_preview(page)
    expect(page.locator("#content .diagram-mermaid svg")).to_be_visible()


def test_file_finder_filters_sidebar(page: Page) -> None:
    open_readme(page)
    page.locator("#finder").fill("install")
    expect(page.locator("#nav a.nav-link")).to_have_count(1)
    expect(page.locator("#nav a.nav-link")).to_contain_text("install.md")


def test_expanded_folders_survive_a_file_change(page: Page) -> None:
    open_readme(page)
    docs = page.locator("#nav details").filter(has=page.locator("summary", has_text="docs"))
    docs.locator("summary").click()
    expect(docs).to_have_attribute("open", "")

    created = WORKSPACE / "scratch.md"
    try:
        created.write_text("# Scratch\n", encoding="utf-8")
        expect(page.locator("#nav a.nav-link", has_text="scratch.md")).to_be_visible()
        expect(docs).to_have_attribute("open", "")
    finally:
        Path(created).unlink(missing_ok=True)

    expect(page.locator("#nav a.nav-link", has_text="scratch.md")).to_have_count(0)
    expect(docs).to_have_attribute("open", "")


def test_content_search_finds_snippet(page: Page) -> None:
    open_readme(page)
    page.locator("#search-mode-content").click()
    page.locator("#finder").fill("'locally via Java")
    expect(page.locator("#nav .content-results a.nav-link")).to_contain_text("README.md")
    expect(page.locator("#nav .search-snippet")).to_contain_text("locally via Java")


def test_csv_viewer_quotes_delimiter_and_skip_lines(page: Page) -> None:
    page.goto("/data.csv")
    rows = page.locator("#csv-table-wrap table tbody tr")
    # header-skip defaults to 0, so the banner comment line is the header row.
    expect(page.locator("#csv-table-wrap thead th").first).to_have_text("generated by acme-export")
    expect(rows).to_have_count(4)

    page.locator("#csv-header-skip").fill("1")
    expect(page.locator("#csv-table-wrap thead th").nth(2)).to_have_text("note")
    expect(rows).to_have_count(3)
    # Quoted field with an embedded comma stays one cell.
    expect(rows.nth(0).locator("td").nth(2)).to_have_text("hello, world")

    page.locator("#csv-footer-skip").fill("1")
    expect(rows).to_have_count(2)


def test_csv_viewer_sorts_by_clicked_column(page: Page) -> None:
    page.goto("/data.csv")
    page.locator("#csv-header-skip").fill("1")
    page.locator("#csv-footer-skip").fill("1")
    rows = page.locator("#csv-table-wrap table tbody tr")
    name_header = page.locator("#csv-table-wrap thead th").first

    name_header.click()
    expect(name_header).to_have_class("sortable sort-asc")
    expect(rows.nth(0).locator("td").first).to_have_text("Ada")

    name_header.click()
    expect(name_header).to_have_class("sortable sort-desc")
    expect(rows.nth(0).locator("td").first).to_have_text("Grace")
